[main]
font=FiraCode Nerd Font:size=12
prompt="> "
lines=15
width=50
horizontal-pad=20
vertical-pad=10
inner-pad=10

[colors]

# Background: Gruvbox Dark Soft ($32302f)
background=32302fff
# Text: Gruvbox FG ($ebdbb2)
text=ebdbb2ff
# Match/Search highlights: Gruvbox Yellow ($fabd2f)
match=fabd2fff
# Selection Background: Gruvbox Gray ($504945)
selection=504945ff
# Selection Text: Gruvbox Light Green ($b8bb26)
selection-text=b8bb26ff
# Selection Match: Gruvbox Orange ($fe8019)
selection-match=fe8019ff
# Border: Gruvbox Aqua/Blue ($83a598)
border=83a598ff
[border]
width=2
radius=8

[dmenu]
mode=text
